version: 2.1
jobs:
   build:
     docker:
       - image: circleci/node:latest
     steps:
       - checkout
       - run: yarn install
       - run: CI=true yarn build
   test:
     docker:
       - image: circleci/node:latest
     steps:
       - checkout
       - run: yarn install
       - run: yarn test
workflows:
  version: 2
  build-test-and-lint:
    jobs:
      - build
      - test